# base16-wezterm (https://github.com/DanielVoogsgerd/base16-wezterm)
# Base16 wezterm template by Daniel Voogsgerd
# IR Black scheme by Timoth√©e Poisot (http://timotheepoisot.fr)

[colors]
foreground = "#b5b3aa"
background = "#000000"

cursor_bg = "#b5b3aa"
cursor_border = "#b5b3aa"
cursor_fg = "#000000"

# selection_bg = "#000000"
# selection_fg = "#000000"

ansi = ["#000000", "#ff6c60", "#a8ff60", "#ffffb6", "#96cbfe", "#ff73fd", "#c6c5fe", "#b5b3aa"]
brights = ["#6c6c66", "#e9c062", "#242422", "#484844", "#918f88", "#d9d7cc", "#b18a3d", "#fdfbee"]

